name: GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"  # Runs every day at 6AM UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: gabriel-dakinah-vincent
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Monrovia
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_followup: yes
          plugin_stars: yes
          plugin_traffic: yes
          plugin_activity: yes
          plugin_achievements: yes
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_repositories: 100
